# hw1

## Q1

Write a function `Print_values` with arguments a, b, and c to reflect the following flowchart. Here the purple parallelogram operator on a list [x, y, z] is to compute and print `x+y-10z`. Try your output with some random a, b, and c values. Report your output when a = 10, b = 5, c = 1.

In [6]:
def Print_values(a,b,c):
    temp =[a,b,c]
    if a>b:
        if b>c:
            temp =[a,b,c]
        elif a>c:
            temp =[a,c,b]
        else:
            temp =[c,a,b]
    elif b>c:
        return ''
    else:
        temp =[c,b,a]

    return temp[0]+temp[1]-10*temp[2]


In [7]:
a =int(input("input vaulue of a: "))
b =int(input("input vaulue of b: "))
c =int(input("input vaulue of c: "))
print(Print_values(a,b,c))

-5


## Q2

Given a list with N positive integers. For every element x of the list, find the value of continuous ceiling function defined as `F(x) = F(ceil(x/3)) + 2x`, where F(1) = 1.

In [9]:
import math

def celing(x):
    if x ==1:
        return 1
    return celing(math.ceil(x/3))+2*x


In [18]:
N =input("input a list of positive intergers of x: ").split(',')

for x in N:
    if x.isdigit() and int(x)>0:
        print(celing(int(x)))
    else:
        print('please input positive intergers')


1
7
13
15
please input positive intergers


## Q3
### 3.1
Given 10 dice each with 6 faces, numbered from 1 to 6. Write a function `Find_number_of_ways` to find the number of ways to get sum x, defined as the sum of values on each face when all the dice are thrown.

In [26]:
def NumberOfways(N, K):
    dp = [0] * (N + 1)
    dp[0] = 1

    for row in range(1, K + 1):
        for col in range(1, N + 1):
            if (col >= row):
                dp[col] = dp[col] + dp[col - row]
    return(dp[N])
 
N = 11
K = 6
 
print(NumberOfways(N, K))

44


### 3.2
Count the number of ways for any x from 10 to 60, assign the number of ways to a list called `Number_of_ways`, so which x yields the maximum of `Number_of_ways`?

## Q4

### 4.1
Write a function `Random_integer` to fill an array of N elements by randomly selecting integers from 0 to 10.

In [39]:
import random
import numpy as np

def Random_integer(N):
    return np.random.randint(11, size =N)

print(Random_integer(5))

[ 1  8 10  2  7]


### 4.2
Write a function `Sum_averages` to compute the sum of the average of all subsets of the array. For example, given an array of [1, 2, 3], you `Sum_averages` function should compute the sum of: average of [1], average of [2], average of [3], average of [1, 2], average of [1, 3], average of [2, 3], and average of [1, 2, 3].


In [77]:
from numpy import *

def Sum_averages(nums):
    res = [[]]
    avg =[]
    for i in range(len(nums)):
        temp = []
        # print(sum)
        for j in range(len(res)):
            temp.append(res[j] + [nums[i]])
            # print(i,j,temp,'--',avg)
            avg.append(mean(temp[j]))
        res += temp
    return sum(avg)

print(Sum_averages([1,2]))

4.5


In [87]:
nums =list(map(int,input("input the list of values: ").split(',')))
print(Sum_averages(nums))

37.5


### 4.3
Call `Sum_averages` with N increasing from 1 to 100, assign the output to a list called `Total_sum_averages`. Plot `Total_sum_averages`, describe what do you see.

In [91]:
Total_sum_averages =[]
for i in range(1,101):
    temp =np.linspace(1,i,num =i)
    Total_sum_averages.append(Sum_averages(temp))

[1.]
[1.0]
[1. 2.]
[1.0, 4.5]
[1. 2. 3.]
[1.0, 4.5, 14.0]
[1. 2. 3. 4.]
[1.0, 4.5, 14.0, 37.5]
[1. 2. 3. 4. 5.]
[1.0, 4.5, 14.0, 37.5, 93.0]
[1. 2. 3. 4. 5. 6.]
[1.0, 4.5, 14.0, 37.5, 93.0, 220.5]
[1. 2. 3. 4. 5. 6. 7.]
[1.0, 4.5, 14.0, 37.5, 93.0, 220.5, 508.00000000000006]
[1. 2. 3. 4. 5. 6. 7. 8.]
[1.0, 4.5, 14.0, 37.5, 93.0, 220.5, 508.00000000000006, 1147.5]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[1.0, 4.5, 14.0, 37.5, 93.0, 220.5, 508.00000000000006, 1147.5, 2555.0]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1.0, 4.5, 14.0, 37.5, 93.0, 220.5, 508.00000000000006, 1147.5, 2555.0, 5626.5]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[1.0, 4.5, 14.0, 37.5, 93.0, 220.5, 508.00000000000006, 1147.5, 2555.0, 5626.5, 12282.0]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
[1.0, 4.5, 14.0, 37.5, 93.0, 220.5, 508.00000000000006, 1147.5, 2555.0, 5626.5, 12282.0, 26617.5]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]
[1.0, 4.5, 14.0, 37.5, 93.0, 220.5, 508.00000000000006, 1147.5, 2555.0, 56

KeyboardInterrupt: 

In [92]:
plot

NameError: name 'plot' is not defined

## 5. Path counting

### 5.1
Create a matrix with N rows and M columns, fill the right-bottom corner and top-left corner cells with 1, and randomly fill the rest of matrix with integer 0 or 1.

In [18]:
import numpy as np

def create_matrix(N,M):
    temp =np.random.randint(0,2,(N,M))
    temp[0,0] =1
    temp[N-1,M-1] =1
    return temp

In [25]:
mat =list(map(int,input("create a matrix with N rows and M columns: ").split(',')))
ran_mat =create_matrix(mat[0],mat[1])
print("The new matrix is: \n",ran_mat)

The new matrix is: 
 [[1 1 0 0 1]
 [0 0 0 1 1]
 [0 0 0 0 0]
 [0 1 1 0 1]]


### 5.2
Consider a cell marked with 0 as a blockage or dead-end, and a cell marked with 1 is good to go. Write a function `Count_path` to count total number of paths to reach the right-bottom corner cell from the top-left corner cell.

### 5.3
Let N = 10, M = 8, run Count_path for 1000 times, each time the matrix (except the right-bottom corner and top-left corner cells, which remain being 1) is re-filled with integer 0 or 1 randomly, report the mean of total number of paths from the 1000 runs.